<?php
/**
 * Schema-Driven Theme Options Definition
 *
 * Defines all 17 tabs and all 16 field types with unique keys, defaults,
 * sanitization rules, and capability requirements.
 *
 * @package ErfanSanat
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Returns the complete theme options tabs metadata.
 *
 * @return array<string, array<string, string>>
 */
function erfan_sanat_get_options_tabs(): array {
	return array(
		'general'     => array(
			'title' => __( 'عمومی', 'erfan-sanat' ),
			'icon'  => 'dashicons-admin-generic',
			'desc'  => __( 'تنظیمات پایه شرکت دانش‌بنیان عرفان صنعت اصفهان و اطلاعات سازمانی.', 'erfan-sanat' ),
		),
		'branding'    => array(
			'title' => __( 'برندینگ و هویت بصری', 'erfan-sanat' ),
			'icon'  => 'dashicons-awards',
			'desc'  => __( 'لوگو، نشان دانش‌بنیان، گواهی ISO 9001 و هویت بصری برند.', 'erfan-sanat' ),
		),
		'header'      => array(
			'title' => __( 'هدر سایت', 'erfan-sanat' ),
			'icon'  => 'dashicons-align-wide',
			'desc'  => __( 'نوار بالایی، هدر چسبان، دکمه مشاوره رایگان و جستجوی سریع.', 'erfan-sanat' ),
		),
		'navigation'  => array(
			'title' => __( 'ناوبری و منوها', 'erfan-sanat' ),
			'icon'  => 'dashicons-menu',
			'desc'  => __( 'رفتار منوی دسکتاپ، مگامنو دسته‌بندی‌ها و منوی کشویی موبایل.', 'erfan-sanat' ),
		),
		'footer'      => array(
			'title' => __( 'فوتر سایت', 'erfan-sanat' ),
			'icon'  => 'dashicons-editor-insertmore',
			'desc'  => __( 'ستون‌های فوتر، متن کپی‌رایت، گواهینامه‌ها و لینک‌های دسترسی سریع.', 'erfan-sanat' ),
		),
		'colors'      => array(
			'title' => __( 'رنگ‌بندی و تم', 'erfan-sanat' ),
			'icon'  => 'dashicons-art',
			'desc'  => __( 'رنگ‌های اصلی، ثانویه، پس‌زمینه تیره صنعتی و متغیرهای پویا CSS.', 'erfan-sanat' ),
		),
		'typography'  => array(
			'title' => __( 'تایپوگرافی و فونت', 'erfan-sanat' ),
			'icon'  => 'dashicons-editor-textcolor',
			'desc'  => __( 'فونت‌های محلی فارسی (وزیرمتن)، اندازه پایه و سلسله‌مراتب تیترها.', 'erfan-sanat' ),
		),
		'homepage'    => array(
			'title' => __( 'صفحه اصلی', 'erfan-sanat' ),
			'icon'  => 'dashicons-admin-home',
			'desc'  => __( 'مدیریت بخش‌های هیرو، نوار شهرها، پروژه‌ها، محصولات، خدمات و آمار.', 'erfan-sanat' ),
		),
		'products'    => array(
			'title' => __( 'کاتالوگ محصولات', 'erfan-sanat' ),
			'icon'  => 'dashicons-lightbulb',
			'desc'  => __( 'تنظیمات نمایش آرشیو محصولات، فیلترهای فنی، دیتاشیت و کاتالوگ PDF.', 'erfan-sanat' ),
		),
		'projects'    => array(
			'title' => __( 'پروژه‌های اجرایی', 'erfan-sanat' ),
			'icon'  => 'dashicons-building',
			'desc'  => __( 'تنظیمات آرشیو و صفحه تکی پروژه‌های نورپردازی شهری.', 'erfan-sanat' ),
		),
		'blog'        => array(
			'title' => __( 'وبلاگ و مقالات فنی', 'erfan-sanat' ),
			'icon'  => 'dashicons-welcome-write-blog',
			'desc'  => __( 'تنظیمات مجله علمی، آموزش کنترلرها، زمان مطالعه و اسکیما سوالات متداول.', 'erfan-sanat' ),
		),
		'woocommerce' => array(
			'title' => __( 'فروشگاه و ووکامرس', 'erfan-sanat' ),
			'icon'  => 'dashicons-cart',
			'desc'  => __( 'مدیریت خرید آنلاین، استعلام تلفنی و مناقصات رسمی شهرداری‌ها.', 'erfan-sanat' ),
		),
		'social'      => array(
			'title' => __( 'شبکه‌های اجتماعی', 'erfan-sanat' ),
			'icon'  => 'dashicons-share',
			'desc'  => __( 'لینک‌های واتساپ، تلگرام، اینستاگرام، آپارات، ایتا و بله.', 'erfan-sanat' ),
		),
		'contact'     => array(
			'title' => __( 'اطلاعات تماس و فروش', 'erfan-sanat' ),
			'icon'  => 'dashicons-phone',
			'desc'  => __( 'شماره‌های تماس ۱۰ خط ویژه، کارشناسان فروش، آدرس کارخانه و ساعات کاری.', 'erfan-sanat' ),
		),
		'seo'         => array(
			'title' => __( 'سئو و اسکیما', 'erfan-sanat' ),
			'icon'  => 'dashicons-search',
			'desc'  => __( 'تنظیمات مسیر راهنما (Breadcrumbs)، Open Graph و داده‌های ساختاریافته.', 'erfan-sanat' ),
		),
		'performance' => array(
			'title' => __( 'کارایی و بهینه‌سازی', 'erfan-sanat' ),
			'icon'  => 'dashicons-performance',
			'desc'  => __( 'بارگذاری تنبل تصاویر، حذف اسکریپت‌های اضافی وردپرس و Defer جاوااسکریپت.', 'erfan-sanat' ),
		),
		'advanced'    => array(
			'title' => __( 'پیشرفته و امنیتی', 'erfan-sanat' ),
			'icon'  => 'dashicons-shield',
			'desc'  => __( 'سخت‌افزار امنیتی، نسخه اسکیما و تنظیمات پیشرفته سیستم.', 'erfan-sanat' ),
		),
	);
}

/**
 * Returns the complete schema array for all theme options.
 *
 * Covers all 17 required tabs and all 16 required field types:
 * text, textarea, number, url, email, color, toggle, select,
 * multiselect, image, gallery, repeater, editor, icon, font, range.
 *
 * @return array<string, array<string, mixed>>
 */
function erfan_sanat_get_options_schema(): array {
	return array(
		// ==================== 1. GENERAL ====================
		'company_legal_name' => array(
			'tab'        => 'general',
			'type'       => 'text',
			'label'      => __( 'نام حقوقی شرکت', 'erfan-sanat' ),
			'desc'       => __( 'نام کامل شرکت در هدر، فوتر و داده‌های ساختاریافته.', 'erfan-sanat' ),
			'default'    => 'شرکت دانش‌بنیان عرفان صنعت اصفهان',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'company_tagline' => array(
			'tab'        => 'general',
			'type'       => 'text',
			'label'      => __( 'شعار سازمانی', 'erfan-sanat' ),
			'desc'       => __( 'زیرعنوان برند در بخش‌های معرفی.', 'erfan-sanat' ),
			'default'    => 'نورپردازی شهری و المان‌های نوری',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'company_established_year' => array(
			'tab'        => 'general',
			'type'       => 'number',
			'label'      => __( 'سال تأسیس (میلادی / شمسی)', 'erfan-sanat' ),
			'desc'       => __( 'سال شروع فعالیت شرکت (مثلاً ۲۰۰۰ یا ۱۳۷۸).', 'erfan-sanat' ),
			'default'    => 2000,
			'min'        => 1350,
			'max'        => 2100,
			'sanitize'   => 'absint',
			'capability' => 'manage_options',
		),
		'company_short_bio' => array(
			'tab'        => 'general',
			'type'       => 'textarea',
			'label'      => __( 'معرفی کوتاه سازمانی', 'erfan-sanat' ),
			'desc'       => __( 'خلاصه معرفی شرکت در فوتر و متا.', 'erfan-sanat' ),
			'default'    => 'با بیش از دو دهه تجربه، پیشگام در طراحی، تولید و اجرای پروژه‌های روشنایی شهری و صنعتی؛ روشنایی‌بخش خیابان‌ها، پارک‌ها، میادین، ساختمان‌ها و صنایع کشور هستیم.',
			'sanitize'   => 'sanitize_textarea_field',
			'capability' => 'manage_options',
		),
		'enable_persian_digits' => array(
			'tab'        => 'general',
			'type'       => 'toggle',
			'label'      => __( 'تبدیل خودکار اعداد به فارسی', 'erfan-sanat' ),
			'desc'       => __( 'تبدیل اعداد انگلیسی به ارقام استاندارد فارسی در فرانت‌اند.', 'erfan-sanat' ),
			'default'    => true,
			'sanitize'   => 'erfan_sanat_sanitize_bool',
			'capability' => 'manage_options',
		),

		// ==================== 2. BRANDING ====================
		'brand_logo_image' => array(
			'tab'        => 'branding',
			'type'       => 'image',
			'label'      => __( 'تصویر لوگو اختصاصی', 'erfan-sanat' ),
			'desc'       => __( 'آپلود یا انتخاب لوگو از کتابخانه رسانه وردپرس.', 'erfan-sanat' ),
			'default'    => ES_THEME_URI . 'assets/images/logo.svg',
			'sanitize'   => 'esc_url_raw',
			'capability' => 'manage_options',
		),
		'brand_badge_text' => array(
			'tab'        => 'branding',
			'type'       => 'text',
			'label'      => __( 'نشان اختصاری برند', 'erfan-sanat' ),
			'desc'       => __( 'حروف اختصاری نشان گرافیکی (مثلاً ES).', 'erfan-sanat' ),
			'default'    => 'ES',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'brand_iso_badge' => array(
			'tab'        => 'branding',
			'type'       => 'text',
			'label'      => __( 'عنوان گواهینامه بین‌المللی', 'erfan-sanat' ),
			'desc'       => __( 'متن نشان گواهینامه در هیرو و بخش درباره ما.', 'erfan-sanat' ),
			'default'    => 'گواهی ISO 9001:2015',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'brand_icon_style' => array(
			'tab'        => 'branding',
			'type'       => 'icon',
			'label'      => __( 'آیکون نماد برند', 'erfan-sanat' ),
			'desc'       => __( 'انتخاب آیکون SVG بومی برای نشان دانش‌بنیان.', 'erfan-sanat' ),
			'default'    => 'spark',
			'options'    => array(
				'spark'   => __( 'ستاره نوری (Spark)', 'erfan-sanat' ),
				'shield'  => __( 'سپر کیفیت (Shield)', 'erfan-sanat' ),
				'bulb'    => __( 'المپ هوشمند (Bulb)', 'erfan-sanat' ),
				'award'   => __( 'نشان استاندارد (Award)', 'erfan-sanat' ),
			),
			'sanitize'   => 'sanitize_key',
			'capability' => 'manage_options',
		),
		'brand_certificates_gallery' => array(
			'tab'        => 'branding',
			'type'       => 'gallery',
			'label'      => __( 'گالری گواهینامه‌ها و افتخارات', 'erfan-sanat' ),
			'desc'       => __( 'شناسه‌های تصاویر گواهینامه ایزو و تاییدیه‌های دانش‌بنیان.', 'erfan-sanat' ),
			'default'    => array(),
			'sanitize'   => 'erfan_sanat_sanitize_gallery',
			'capability' => 'manage_options',
		),

		// ==================== 3. HEADER ====================
		'header_sticky' => array(
			'tab'        => 'header',
			'type'       => 'toggle',
			'label'      => __( 'هدر چسبان هوشمند (Sticky Header)', 'erfan-sanat' ),
			'desc'       => __( 'ثابت ماندن هدر با افکت شیشه‌ای هنگام اسکرول صفحه.', 'erfan-sanat' ),
			'default'    => true,
			'sanitize'   => 'erfan_sanat_sanitize_bool',
			'capability' => 'manage_options',
		),
		'header_show_topbar' => array(
			'tab'        => 'header',
			'type'       => 'toggle',
			'label'      => __( 'نمایش نوار اطلاع‌رسانی بالایی', 'erfan-sanat' ),
			'desc'       => __( 'نمایش تلفن ۱۰ خط ویژه، گواهی ISO و ساعات کاری در بالای هدر.', 'erfan-sanat' ),
			'default'    => true,
			'sanitize'   => 'erfan_sanat_sanitize_bool',
			'capability' => 'manage_options',
		),
		'header_cta_text' => array(
			'tab'        => 'header',
			'type'       => 'text',
			'label'      => __( 'متن دکمه فراخوان هدر', 'erfan-sanat' ),
			'desc'       => __( 'عنوان دکمه اصلی در سمت چپ هدر.', 'erfan-sanat' ),
			'default'    => 'دریافت مشاوره رایگان',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'header_cta_url' => array(
			'tab'        => 'header',
			'type'       => 'url',
			'label'      => __( 'لینک دکمه فراخوان هدر', 'erfan-sanat' ),
			'desc'       => __( 'آدرس مقصد دکمه مشاوره در هدر.', 'erfan-sanat' ),
			'default'    => '#consultation',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'header_show_search' => array(
			'tab'        => 'header',
			'type'       => 'toggle',
			'label'      => __( 'نمایش جستجو در هدر', 'erfan-sanat' ),
			'desc'       => __( 'امکان جستجوی سریع در محصولات، پروژه‌ها و مقالات.', 'erfan-sanat' ),
			'default'    => true,
			'sanitize'   => 'erfan_sanat_sanitize_bool',
			'capability' => 'manage_options',
		),

		// ==================== 4. NAVIGATION ====================
		'nav_show_product_cats_dropdown' => array(
			'tab'        => 'navigation',
			'type'       => 'toggle',
			'label'      => __( 'نمایش زیرمنوی خودکار دسته‌بندی محصولات', 'erfan-sanat' ),
			'desc'       => __( 'نمایش دسته‌بندی‌های اصلی تجهیزات نورپردازی در منوی اصلی.', 'erfan-sanat' ),
			'default'    => true,
			'sanitize'   => 'erfan_sanat_sanitize_bool',
			'capability' => 'manage_options',
		),
		'nav_mobile_style' => array(
			'tab'        => 'navigation',
			'type'       => 'select',
			'label'      => __( 'سبک منوی موبایل', 'erfan-sanat' ),
			'desc'       => __( 'نحوه باز شدن منوی ناوبری در تبلت و موبایل.', 'erfan-sanat' ),
			'default'    => 'drawer-rtl',
			'options'    => array(
				'drawer-rtl' => __( 'کشویی از سمت راست (RTL Drawer)', 'erfan-sanat' ),
				'fullscreen' => __( 'تمام‌صفحه (Fullscreen Overlay)', 'erfan-sanat' ),
			),
			'sanitize'   => 'sanitize_key',
			'capability' => 'manage_options',
		),
		'nav_highlight_items' => array(
			'tab'        => 'navigation',
			'type'       => 'multiselect',
			'label'      => __( 'بخش‌های برجسته در ناوبری سریع', 'erfan-sanat' ),
			'desc'       => __( 'انتخاب بخش‌های کلیدی جهت نمایش در دسترسی سریع.', 'erfan-sanat' ),
			'default'    => array( 'products', 'projects', 'services', 'blog', 'contact' ),
			'options'    => array(
				'products' => __( 'محصولات نورپردازی', 'erfan-sanat' ),
				'projects' => __( 'پروژه‌های شهری', 'erfan-sanat' ),
				'services' => __( 'خدمات نورپردازی', 'erfan-sanat' ),
				'blog'     => __( 'مقالات فنی', 'erfan-sanat' ),
				'contact'  => __( 'مشاوره و تماس', 'erfan-sanat' ),
			),
			'sanitize'   => 'erfan_sanat_sanitize_multiselect',
			'capability' => 'manage_options',
		),

		// ==================== 5. FOOTER ====================
		'footer_about_editor' => array(
			'tab'        => 'footer',
			'type'       => 'editor',
			'label'      => __( 'متن معرفی شرکت در فوتر', 'erfan-sanat' ),
			'desc'       => __( 'توضیحات غنی درباره شرکت دانش‌بنیان عرفان صنعت اصفهان.', 'erfan-sanat' ),
			'default'    => '<p><strong>شرکت دانش‌بنیان عرفان صنعت اصفهان</strong> با بیش از ۲۵ سال سابقه درخشان و گواهینامه بین‌المللی ISO 9001:2015، پیشگام در طراحی، تولید و اجرای پروژه‌های نورپردازی شهری، المان‌های حجمی، ریسه‌های LED و سیستم‌های کنترل هوشمند در سراسر ایران است.</p>',
			'sanitize'   => 'wp_kses_post',
			'capability' => 'manage_options',
		),
		'footer_copyright_text' => array(
			'tab'        => 'footer',
			'type'       => 'text',
			'label'      => __( 'متن کپی‌رایت فوتر', 'erfan-sanat' ),
			'desc'       => __( 'متن حقوق مادی و معنوی در انتهای سایت.', 'erfan-sanat' ),
			'default'    => 'تمامی حقوق این وب‌سایت متعلق به شرکت دانش‌بنیان عرفان صنعت اصفهان می‌باشد.',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'footer_show_trust_badges' => array(
			'tab'        => 'footer',
			'type'       => 'toggle',
			'label'      => __( 'نمایش نشان‌های اعتماد و استاندارد در فوتر', 'erfan-sanat' ),
			'desc'       => __( 'نمایش گواهی ISO 9001:2015، دانش‌بنیان، IP67/IP68 و ۲۴ ماه گارانتی.', 'erfan-sanat' ),
			'default'    => true,
			'sanitize'   => 'erfan_sanat_sanitize_bool',
			'capability' => 'manage_options',
		),

		// ==================== 6. COLORS ====================
		'color_primary' => array(
			'tab'        => 'colors',
			'type'       => 'color',
			'label'      => __( 'رنگ اصلی برند (طلایی/کهربایی نور)', 'erfan-sanat' ),
			'desc'       => __( 'متغیر --es-primary برای دکمه‌های اصلی، نشان‌ها و درخشش‌ها.', 'erfan-sanat' ),
			'default'    => '#f59e0b',
			'sanitize'   => 'sanitize_hex_color',
			'capability' => 'manage_options',
		),
		'color_secondary' => array(
			'tab'        => 'colors',
			'type'       => 'color',
			'label'      => __( 'رنگ ثانویه (آبی الکتریک/سیان)', 'erfan-sanat' ),
			'desc'       => __( 'متغیر --es-secondary برای تاکیدهای فناوری و پروتکل‌های هوشمند.', 'erfan-sanat' ),
			'default'    => '#0ea5e9',
			'sanitize'   => 'sanitize_hex_color',
			'capability' => 'manage_options',
		),
		'color_accent' => array(
			'tab'        => 'colors',
			'type'       => 'color',
			'label'      => __( 'رنگ تاکیدی (طلایی روشن)', 'erfan-sanat' ),
			'desc'       => __( 'متغیر --es-accent برای هاورها و هایلایت تیترها.', 'erfan-sanat' ),
			'default'    => '#fbbf24',
			'sanitize'   => 'sanitize_hex_color',
			'capability' => 'manage_options',
		),
		'color_background' => array(
			'tab'        => 'colors',
			'type'       => 'color',
			'label'      => __( 'رنگ پس‌زمینه اصلی (شب شهری)', 'erfan-sanat' ),
			'desc'       => __( 'متغیر --es-background برای پس‌زمینه کلی صفحات.', 'erfan-sanat' ),
			'default'    => '#090d16',
			'sanitize'   => 'sanitize_hex_color',
			'capability' => 'manage_options',
		),
		'color_surface' => array(
			'tab'        => 'colors',
			'type'       => 'color',
			'label'      => __( 'رنگ سطح کارت‌ها و پنل‌ها', 'erfan-sanat' ),
			'desc'       => __( 'متغیر --es-surface برای کارت‌های محصول، پروژه و باکس‌ها.', 'erfan-sanat' ),
			'default'    => '#111827',
			'sanitize'   => 'sanitize_hex_color',
			'capability' => 'manage_options',
		),
		'color_text' => array(
			'tab'        => 'colors',
			'type'       => 'color',
			'label'      => __( 'رنگ متن اصلی', 'erfan-sanat' ),
			'desc'       => __( 'متغیر --es-text برای متون اصلی و تیترها.', 'erfan-sanat' ),
			'default'    => '#f8fafc',
			'sanitize'   => 'sanitize_hex_color',
			'capability' => 'manage_options',
		),
		'color_muted' => array(
			'tab'        => 'colors',
			'type'       => 'color',
			'label'      => __( 'رنگ متن فرعی (Muted)', 'erfan-sanat' ),
			'desc'       => __( 'متغیر --es-muted برای توضیحات فرعی و زیرعنوان‌ها.', 'erfan-sanat' ),
			'default'    => '#94a3b8',
			'sanitize'   => 'sanitize_hex_color',
			'capability' => 'manage_options',
		),
		'color_border' => array(
			'tab'        => 'colors',
			'type'       => 'color',
			'label'      => __( 'رنگ خطوط حاشیه (Border)', 'erfan-sanat' ),
			'desc'       => __( 'متغیر --es-border برای خطوط جداکننده و کادرها.', 'erfan-sanat' ),
			'default'    => '#1e293b',
			'sanitize'   => 'sanitize_hex_color',
			'capability' => 'manage_options',
		),
		'ui_border_radius' => array(
			'tab'        => 'colors',
			'type'       => 'range',
			'label'      => __( 'شعاع انحنای کارت‌ها (پیکسل)', 'erfan-sanat' ),
			'desc'       => __( 'متغیر --es-radius برای گردی گوشه‌های کارت‌ها و دکمه‌ها.', 'erfan-sanat' ),
			'default'    => 16,
			'min'        => 4,
			'max'        => 32,
			'step'       => 2,
			'sanitize'   => 'absint',
			'capability' => 'manage_options',
		),
		'ui_container_width' => array(
			'tab'        => 'colors',
			'type'       => 'range',
			'label'      => __( 'حداکثر عرض کانتینر (پیکسل)', 'erfan-sanat' ),
			'desc'       => __( 'متغیر --es-container برای عرض محتوای اصلی سایت.', 'erfan-sanat' ),
			'default'    => 1320,
			'min'        => 1140,
			'max'        => 1560,
			'step'       => 20,
			'sanitize'   => 'absint',
			'capability' => 'manage_options',
		),

		// ==================== 7. TYPOGRAPHY ====================
		'font_body' => array(
			'tab'        => 'typography',
			'type'       => 'font',
			'label'      => __( 'فونت متن اصلی (محلی)', 'erfan-sanat' ),
			'desc'       => __( 'متغیر --es-font-body با بارگذاری ۱۰۰٪ محلی بدون CDN.', 'erfan-sanat' ),
			'default'    => 'Vazirmatn',
			'options'    => array(
				'Vazirmatn' => __( 'وزیرمتن (Vazirmatn Local WOFF2)', 'erfan-sanat' ),
				'Tahoma'    => __( 'تاهوما (System Tahoma)', 'erfan-sanat' ),
			),
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'font_heading' => array(
			'tab'        => 'typography',
			'type'       => 'font',
			'label'      => __( 'فونت تیترها و عناوین (محلی)', 'erfan-sanat' ),
			'desc'       => __( 'متغیر --es-font-heading برای تیترهای صفحه.', 'erfan-sanat' ),
			'default'    => 'Vazirmatn',
			'options'    => array(
				'Vazirmatn' => __( 'وزیرمتن بولد (Vazirmatn Bold/ExtraBold)', 'erfan-sanat' ),
				'Tahoma'    => __( 'تاهوما (System Tahoma)', 'erfan-sanat' ),
			),
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'font_base_size' => array(
			'tab'        => 'typography',
			'type'       => 'range',
			'label'      => __( 'اندازه پایه فونت (پیکسل)', 'erfan-sanat' ),
			'desc'       => __( 'اندازه پیش‌فرض متن بدنه در دسکتاپ.', 'erfan-sanat' ),
			'default'    => 16,
			'min'        => 14,
			'max'        => 20,
			'step'       => 1,
			'sanitize'   => 'absint',
			'capability' => 'manage_options',
		),

		// ==================== 8. HOMEPAGE ====================
		'hero_badge_text' => array(
			'tab'        => 'homepage',
			'type'       => 'text',
			'label'      => __( 'برچسب بالای تیتر هیرو', 'erfan-sanat' ),
			'desc'       => __( 'متن نشان بالای عنوان اصلی در بخش Hero.', 'erfan-sanat' ),
			'default'    => 'شرکت دانش‌بنیان عرفان صنعت اصفهان',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'hero_title' => array(
			'tab'        => 'homepage',
			'type'       => 'text',
			'label'      => __( 'عنوان اصلی هیرو (H1)', 'erfan-sanat' ),
			'desc'       => __( 'تیتر اول صفحه اصلی مطابق طراحی مرجع.', 'erfan-sanat' ),
			'default'    => 'درخشان‌تر از همیشه، آینده‌ای روشن برای ایران می‌سازیم',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'hero_subtitle' => array(
			'tab'        => 'homepage',
			'type'       => 'textarea',
			'label'      => __( 'زیرعنوان بخش هیرو', 'erfan-sanat' ),
			'desc'       => __( 'توضیحات زیر تیتر اصلی در بخش هیرو.', 'erfan-sanat' ),
			'default'    => 'با بیش از دو دهه تجربه، پیشگام در طراحی، تولید و اجرای پروژه‌های روشنایی شهری و صنعتی؛ روشنایی‌بخش خیابان‌ها، پارک‌ها، میادین، ساختمان‌ها و صنایع کشور هستیم.',
			'sanitize'   => 'sanitize_textarea_field',
			'capability' => 'manage_options',
		),
		'hero_bg_image' => array(
			'tab'        => 'homepage',
			'type'       => 'image',
			'label'      => __( 'تصویر پس‌زمینه هیرو', 'erfan-sanat' ),
			'desc'       => __( 'تصویر شاخص نورپردازی شهری در بخش هیرو.', 'erfan-sanat' ),
			'default'    => ES_THEME_URI . 'assets/images/hero.jpg',
			'sanitize'   => 'esc_url_raw',
			'capability' => 'manage_options',
		),
		'hero_stats_repeater' => array(
			'tab'        => 'homepage',
			'type'       => 'repeater',
			'label'      => __( 'آمارهای کلیدی بخش هیرو و درباره ما', 'erfan-sanat' ),
			'desc'       => __( 'لیست شمارنده‌های افتخارات شرکت.', 'erfan-sanat' ),
			'default'    => array(
				array(
					'number' => '۲۵+',
					'label'  => 'سال تجربه درخشان',
				),
				array(
					'number' => '۸۵۰+',
					'label'  => 'پروژه تکمیل‌شده',
				),
				array(
					'number' => '۲۸۹+',
					'label'  => 'مشتری فعال',
				),
				array(
					'number' => '۹۰+',
					'label'  => 'محصول متنوع',
				),
			),
			'fields'     => array(
				'number' => array(
					'type'  => 'text',
					'label' => __( 'عدد / مقدار', 'erfan-sanat' ),
				),
				'label'  => array(
					'type'  => 'text',
					'label' => __( 'عنوان آمار', 'erfan-sanat' ),
				),
			),
			'sanitize'   => 'erfan_sanat_sanitize_repeater',
			'capability' => 'manage_options',
		),
		'home_partner_cities' => array(
			'tab'        => 'homepage',
			'type'       => 'text',
			'label'      => __( 'شهرهای همکار (نوار متحرک)', 'erfan-sanat' ),
			'desc'       => __( 'نام شهرها را با کاما (،) جدا کنید.', 'erfan-sanat' ),
			'default'    => 'اصفهان، تهران، شیراز، مشهد، کرمان، البرز، تبریز، اهواز، قم، رشت، یزد، اردبیل، خراسان، گیلان، کیش، چابهار، قزوین، کاشان، بندرعباس، همدان، زنجان، ساری، ارومیه، بوشهر',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'home_about_title' => array(
			'tab'        => 'homepage',
			'type'       => 'text',
			'label'      => __( 'عنوان بخش درباره شرکت در صفحه اصلی', 'erfan-sanat' ),
			'desc'       => __( 'تیتر بخش معرفی شرکت دانش‌بنیان.', 'erfan-sanat' ),
			'default'    => 'بیش از ۲۵ سال تجربه، حاصلِ کارِ مفیدِ بی‌وقفه',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),

		// ==================== 9. PRODUCTS ====================
		'products_archive_title' => array(
			'tab'        => 'products',
			'type'       => 'text',
			'label'      => __( 'عنوان آرشیو محصولات', 'erfan-sanat' ),
			'desc'       => __( 'عنوان هدر فروشگاه تجهیزات نورپردازی شهری.', 'erfan-sanat' ),
			'default'    => 'فروشگاه تجهیزات نورپردازی شهری و محصولات دانش‌بنیان',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'products_catalog_pdf_url' => array(
			'tab'        => 'products',
			'type'       => 'url',
			'label'      => __( 'لینک دانلود کاتالوگ جامع (PDF)', 'erfan-sanat' ),
			'desc'       => __( 'فایل PDF کاتالوگ محصولات جهت دانلود مستقیم شهرداری‌ها و پیمانکاران.', 'erfan-sanat' ),
			'default'    => ES_THEME_URI . 'assets/images/sample-datasheet.pdf',
			'sanitize'   => 'esc_url_raw',
			'capability' => 'manage_options',
		),
		'products_per_page' => array(
			'tab'        => 'products',
			'type'       => 'number',
			'label'      => __( 'تعداد محصولات در هر صفحه', 'erfan-sanat' ),
			'desc'       => __( 'تعداد کارت‌های محصول در صفحات آرشیو فروشگاه.', 'erfan-sanat' ),
			'default'    => 12,
			'min'        => 4,
			'max'        => 48,
			'sanitize'   => 'absint',
			'capability' => 'manage_options',
		),
		'products_show_tech_badges' => array(
			'tab'        => 'products',
			'type'       => 'toggle',
			'label'      => __( 'نمایش نشان‌های فنی (IP / ولتاژ / پروتکل) روی کارت محصول', 'erfan-sanat' ),
			'desc'       => __( 'نمایش ویژگی‌های مهندسی روی کارت‌های محصول در آرشیو و صفحه اصلی.', 'erfan-sanat' ),
			'default'    => true,
			'sanitize'   => 'erfan_sanat_sanitize_bool',
			'capability' => 'manage_options',
		),

		// ==================== 10. PROJECTS ====================
		'projects_archive_title' => array(
			'tab'        => 'projects',
			'type'       => 'text',
			'label'      => __( 'عنوان آرشیو پروژه‌های نورپردازی', 'erfan-sanat' ),
			'desc'       => __( 'تیتر اصلی صفحه آرشیو پروژه‌ها (/projects/).', 'erfan-sanat' ),
			'default'    => 'پروژه‌های نورپردازی شهری',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'projects_archive_subtitle' => array(
			'tab'        => 'projects',
			'type'       => 'textarea',
			'label'      => __( 'توضیحات آرشیو پروژه‌ها', 'erfan-sanat' ),
			'desc'       => __( 'زیرعنوان صفحه نمونه پروژه‌های اجرایی.', 'erfan-sanat' ),
			'default'    => 'نمونه پروژه‌های نورپردازی حرفه‌ای شهری؛ هر پروژه، روایتی از هنر، مهندسی و نور است که هویت بصری شهر را برای همیشه دگرگون می‌کند.',
			'sanitize'   => 'sanitize_textarea_field',
			'capability' => 'manage_options',
		),
		'projects_per_page' => array(
			'tab'        => 'projects',
			'type'       => 'number',
			'label'      => __( 'تعداد پروژه‌ها در هر صفحه', 'erfan-sanat' ),
			'desc'       => __( 'تعداد کارت‌های پروژه در آرشیو.', 'erfan-sanat' ),
			'default'    => 9,
			'min'        => 3,
			'max'        => 36,
			'sanitize'   => 'absint',
			'capability' => 'manage_options',
		),

		// ==================== 11. BLOG ====================
		'blog_archive_title' => array(
			'tab'        => 'blog',
			'type'       => 'text',
			'label'      => __( 'عنوان مجله فنی و وبلاگ', 'erfan-sanat' ),
			'desc'       => __( 'تیتر اصلی صفحه وبلاگ و مقالات تخصصی (/blog/).', 'erfan-sanat' ),
			'default'    => 'پایگاه دانش و مقالات تخصصی نورپردازی شهری',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'blog_show_reading_time' => array(
			'tab'        => 'blog',
			'type'       => 'toggle',
			'label'      => __( 'نمایش زمان مطالعه و بازبین فنی مقاله', 'erfan-sanat' ),
			'desc'       => __( 'نمایش متادیتای مهندسی مقالات در کارت‌ها و بالای مقاله.', 'erfan-sanat' ),
			'default'    => true,
			'sanitize'   => 'erfan_sanat_sanitize_bool',
			'capability' => 'manage_options',
		),
		'blog_enable_faq_schema' => array(
			'tab'        => 'blog',
			'type'       => 'toggle',
			'label'      => __( 'خروجی خودکار اسکیما FAQPage در مقالات', 'erfan-sanat' ),
			'desc'       => __( 'تولید JSON-LD استاندارد برای سوالات متداول ثبت‌شده در مقالات.', 'erfan-sanat' ),
			'default'    => true,
			'sanitize'   => 'erfan_sanat_sanitize_bool',
			'capability' => 'manage_options',
		),

		// ==================== 12. WOOCOMMERCE ====================
		'wc_default_order_type' => array(
			'tab'        => 'woocommerce',
			'type'       => 'select',
			'label'      => __( 'حالت پیش‌فرض سفارش محصولات', 'erfan-sanat' ),
			'desc'       => __( 'در صورتی که برای محصولی حالت سفارش مشخص نشده باشد.', 'erfan-sanat' ),
			'default'    => 'online_cart',
			'options'    => array(
				'online_cart'     => __( 'خرید آنلاین (افزودن به سبد خرید)', 'erfan-sanat' ),
				'phone_inquiry'   => __( 'استعلام قیمت تلفنی با کارشناسان فروش', 'erfan-sanat' ),
				'official_tender' => __( 'مناقصه رسمی و درخواست پیش‌فاکتور سازمانی', 'erfan-sanat' ),
			),
			'sanitize'   => 'sanitize_key',
			'capability' => 'manage_options',
		),
		'wc_default_inquiry_phone' => array(
			'tab'        => 'woocommerce',
			'type'       => 'text',
			'label'      => __( 'شماره پیش‌فرض استعلام قیمت محصولات', 'erfan-sanat' ),
			'desc'       => __( 'شماره تماس نمایش داده‌شده در محصولات استعلامی.', 'erfan-sanat' ),
			'default'    => '031-91091011',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'wc_tender_cta_label' => array(
			'tab'        => 'woocommerce',
			'type'       => 'text',
			'label'      => __( 'متن دکمه استعلام مناقصه و پیش‌فاکتور رسمی', 'erfan-sanat' ),
			'desc'       => __( 'متن دکمه برای محصولات پروژه‌ای و مناقصه‌ای شهرداری‌ها.', 'erfan-sanat' ),
			'default'    => 'درخواست پیش‌فاکتور رسمی و شرایط مناقصه',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'wc_warranty_badge_text' => array(
			'tab'        => 'woocommerce',
			'type'       => 'text',
			'label'      => __( 'متن تضمین گارانتی در صفحه محصول', 'erfan-sanat' ),
			'desc'       => __( 'نشان اطمینان خرید در بالای اطلاعات محصول.', 'erfan-sanat' ),
			'default'    => '۲۴ ماه گارانتی تعویض + ۵ سال خدمات پس از فروش',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),

		// ==================== 13. SOCIAL ====================
		'social_whatsapp' => array(
			'tab'        => 'social',
			'type'       => 'url',
			'label'      => __( 'لینک واتساپ پشتیبانی فروش', 'erfan-sanat' ),
			'desc'       => __( 'آدرس ارتباط مستقیم در واتساپ.', 'erfan-sanat' ),
			'default'    => 'https://api.whatsapp.com/send?phone=989137976915',
			'sanitize'   => 'esc_url_raw',
			'capability' => 'manage_options',
		),
		'social_telegram' => array(
			'tab'        => 'social',
			'type'       => 'url',
			'label'      => __( 'لینک کانال تلگرام', 'erfan-sanat' ),
			'desc'       => __( 'آدرس کانال رسمی تلگرام شرکت.', 'erfan-sanat' ),
			'default'    => 'https://t.me/s/erfansanat',
			'sanitize'   => 'esc_url_raw',
			'capability' => 'manage_options',
		),
		'social_instagram' => array(
			'tab'        => 'social',
			'type'       => 'url',
			'label'      => __( 'لینک صفحه اینستاگرام', 'erfan-sanat' ),
			'desc'       => __( 'آدرس اینستاگرام عرفان صنعت اصفهان.', 'erfan-sanat' ),
			'default'    => 'https://www.instagram.com/erfansanat_com',
			'sanitize'   => 'esc_url_raw',
			'capability' => 'manage_options',
		),
		'social_aparat' => array(
			'tab'        => 'social',
			'type'       => 'url',
			'label'      => __( 'لینک کانال آپارات (ویدیو پروژه‌ها)', 'erfan-sanat' ),
			'desc'       => __( 'آدرس صفحه رسمی آپارات شرکت.', 'erfan-sanat' ),
			'default'    => 'https://www.aparat.com/erfansanat',
			'sanitize'   => 'esc_url_raw',
			'capability' => 'manage_options',
		),
		'social_eitaa' => array(
			'tab'        => 'social',
			'type'       => 'url',
			'label'      => __( 'لینک کانال ایتا', 'erfan-sanat' ),
			'desc'       => __( 'آدرس کانال ایتا عرفان صنعت.', 'erfan-sanat' ),
			'default'    => 'https://eitaa.com/erfansanat',
			'sanitize'   => 'esc_url_raw',
			'capability' => 'manage_options',
		),

		// ==================== 14. CONTACT ====================
		'contact_phone_main' => array(
			'tab'        => 'contact',
			'type'       => 'text',
			'label'      => __( 'تلفن مرکزی (۱۰ خط ویژه)', 'erfan-sanat' ),
			'desc'       => __( 'شماره تماس اصلی کارخانه و دفتر فروش.', 'erfan-sanat' ),
			'default'    => '۰۳۱-۹۱۰۹۱۰۱۱',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'contact_phone_tel_link' => array(
			'tab'        => 'contact',
			'type'       => 'text',
			'label'      => __( 'شماره تماس جهت لینک tel:', 'erfan-sanat' ),
			'desc'       => __( 'شماره انگلیسی بدون فاصله برای پروتکل تماس.', 'erfan-sanat' ),
			'default'    => '03191091011',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'contact_email' => array(
			'tab'        => 'contact',
			'type'       => 'email',
			'label'      => __( 'پست الکترونیکی رسمی', 'erfan-sanat' ),
			'desc'       => __( 'ایمیل سازمانی جهت مکاتبات و استعلام‌ها.', 'erfan-sanat' ),
			'default'    => 'info@erfansanat.com',
			'sanitize'   => 'sanitize_email',
			'capability' => 'manage_options',
		),
		'contact_working_hours' => array(
			'tab'        => 'contact',
			'type'       => 'text',
			'label'      => __( 'ساعات کاری شرکت', 'erfan-sanat' ),
			'desc'       => __( 'ساعات پاسخگویی واحد فروش و فنی.', 'erfan-sanat' ),
			'default'    => '۷ صبح تا ۴:۳۰ بعدازظهر (شنبه تا پنجشنبه)',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'contact_address' => array(
			'tab'        => 'contact',
			'type'       => 'textarea',
			'label'      => __( 'نشانی کارخانه و دفتر مرکزی', 'erfan-sanat' ),
			'desc'       => __( 'آدرس پستی کامل شرکت در شهرک صنعتی برق و الکترونیک.', 'erfan-sanat' ),
			'default'    => 'اصفهان، شهرستان خمینی‌شهر، شهرک صنعتی برق و الکترونیک، بلوار الکترونیک، پلاک ۱۱۹',
			'sanitize'   => 'sanitize_textarea_field',
			'capability' => 'manage_options',
		),
		'contact_postal_code' => array(
			'tab'        => 'contact',
			'type'       => 'text',
			'label'      => __( 'کد پستی ۱۰ رقمی', 'erfan-sanat' ),
			'desc'       => __( 'کد پستی رسمی کارخانه.', 'erfan-sanat' ),
			'default'    => '۸۴۱۸۱۴۸۶۷۸',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
		'contact_sales_team_repeater' => array(
			'tab'        => 'contact',
			'type'       => 'repeater',
			'label'      => __( 'کارشناسان فروش و پشتیبانی فنی', 'erfan-sanat' ),
			'desc'       => __( 'لیست کارشناسان فروش در صفحه تماس با ما.', 'erfan-sanat' ),
			'default'    => array(
				array(
					'name'  => 'مهندس محمدعلی قربانی',
					'role'  => 'مدیر فروش',
					'phone' => '09137976915',
				),
				array(
					'name'  => 'مهندس علی حیدری',
					'role'  => 'سرپرست فروش',
					'phone' => '09130559026',
				),
				array(
					'name'  => 'مهندس فرزین داستانیان',
					'role'  => 'کارشناس فروش پروژه‌های شهری',
					'phone' => '09130559025',
				),
				array(
					'name'  => 'مهندس مرتضی کامرانی',
					'role'  => 'پشتیبانی فنی و فروش',
					'phone' => '09139330097',
				),
			),
			'fields'     => array(
				'name'  => array(
					'type'  => 'text',
					'label' => __( 'نام کارشناس', 'erfan-sanat' ),
				),
				'role'  => array(
					'type'  => 'text',
					'label' => __( 'سمت سازمانی', 'erfan-sanat' ),
				),
				'phone' => array(
					'type'  => 'text',
					'label' => __( 'شماره همراه مستقیم', 'erfan-sanat' ),
				),
			),
			'sanitize'   => 'erfan_sanat_sanitize_repeater',
			'capability' => 'manage_options',
		),

		// ==================== 15. SEO ====================
		'seo_enable_breadcrumbs' => array(
			'tab'        => 'seo',
			'type'       => 'toggle',
			'label'      => __( 'فعال‌سازی مسیر راهنما (Breadcrumbs)', 'erfan-sanat' ),
			'desc'       => __( 'نمایش مسیر سلسله‌مراتبی صفحات به همراه اسکیما BreadcrumbList.', 'erfan-sanat' ),
			'default'    => true,
			'sanitize'   => 'erfan_sanat_sanitize_bool',
			'capability' => 'manage_options',
		),
		'seo_enable_og_tags' => array(
			'tab'        => 'seo',
			'type'       => 'toggle',
			'label'      => __( 'تولید متاتگ‌های Open Graph بومی', 'erfan-sanat' ),
			'desc'       => __( 'تنها در صورتی که افزونه سئو (Yoast / RankMath) فعال نباشد اجرا می‌شود.', 'erfan-sanat' ),
			'default'    => true,
			'sanitize'   => 'erfan_sanat_sanitize_bool',
			'capability' => 'manage_options',
		),
		'seo_enable_org_schema' => array(
			'tab'        => 'seo',
			'type'       => 'toggle',
			'label'      => __( 'تولید اسکیما Organization و LocalBusiness', 'erfan-sanat' ),
			'desc'       => __( 'تولید داده‌های ساختاریافته JSON-LD برای شرکت دانش‌بنیان عرفان صنعت.', 'erfan-sanat' ),
			'default'    => true,
			'sanitize'   => 'erfan_sanat_sanitize_bool',
			'capability' => 'manage_options',
		),

		// ==================== 16. PERFORMANCE ====================
		'perf_disable_wp_emojis' => array(
			'tab'        => 'performance',
			'type'       => 'toggle',
			'label'      => __( 'غیرفعال‌سازی اسکریپت ایموجی‌های وردپرس', 'erfan-sanat' ),
			'desc'       => __( 'حذف درخواست‌های اضافی wp-emoji-release.min.js در فرانت‌اند.', 'erfan-sanat' ),
			'default'    => true,
			'sanitize'   => 'erfan_sanat_sanitize_bool',
			'capability' => 'manage_options',
		),
		'perf_defer_theme_js' => array(
			'tab'        => 'performance',
			'type'       => 'toggle',
			'label'      => __( 'بارگذاری غیرمسدودکننده (Defer) جاوااسکریپت پوسته', 'erfan-sanat' ),
			'desc'       => __( 'افزودن ویژگی defer به اسکریپت‌های فرانت‌اند برای بهبود سرعت رندر.', 'erfan-sanat' ),
			'default'    => true,
			'sanitize'   => 'erfan_sanat_sanitize_bool',
			'capability' => 'manage_options',
		),
		'perf_lazy_load_images' => array(
			'tab'        => 'performance',
			'type'       => 'toggle',
			'label'      => __( 'بارگذاری تنبل (Lazy Loading) تصاویر و ویدیوها', 'erfan-sanat' ),
			'desc'       => __( 'افزودن ویژگی loading="lazy" و decoding="async" به تصاویر محتوا.', 'erfan-sanat' ),
			'default'    => true,
			'sanitize'   => 'erfan_sanat_sanitize_bool',
			'capability' => 'manage_options',
		),

		// ==================== 17. ADVANCED ====================
		'adv_security_headers' => array(
			'tab'        => 'advanced',
			'type'       => 'toggle',
			'label'      => __( 'ارسال هدرهای امنیتی پایه (X-Content-Type-Options / Referrer-Policy)', 'erfan-sanat' ),
			'desc'       => __( 'افزایش امنیت پاسخ‌های HTTP در برابر حملات رایج.', 'erfan-sanat' ),
			'default'    => true,
			'sanitize'   => 'erfan_sanat_sanitize_bool',
			'capability' => 'manage_options',
		),
		'adv_hide_wp_version' => array(
			'tab'        => 'advanced',
			'type'       => 'toggle',
			'label'      => __( 'مخفی‌سازی نسخه وردپرس در متاتگ Generator', 'erfan-sanat' ),
			'desc'       => __( 'حذف اطلاعات نسخه وردپرس از سورس HTML و فیدهای RSS.', 'erfan-sanat' ),
			'default'    => true,
			'sanitize'   => 'erfan_sanat_sanitize_bool',
			'capability' => 'manage_options',
		),
		'adv_schema_version' => array(
			'tab'        => 'advanced',
			'type'       => 'text',
			'label'      => __( 'نسخه اسکیما تنظیمات', 'erfan-sanat' ),
			'desc'       => __( 'نسخه ساختار دیتابیس تنظیمات پوسته جهت مهاجرت خودکار.', 'erfan-sanat' ),
			'default'    => '1.0.0',
			'sanitize'   => 'sanitize_text_field',
			'capability' => 'manage_options',
		),
	);
}
